Process an empty YAML when a configuration file isn't provided
eProsima/Fast-DDS-spy pull request #62
Opened 2023-12-14 10:41 UTC by Tempate

In the previous version, when a user didn't provide a configuration file, the Fast-DDS Spy didn't process the default YAML configuration. To fix it, in this version when a configuration file isn't provided, the Fast-DDS Spy processes an empty YAML into which it loads the default YAML configuration.

2023-12-18 14:40 UTC, irenebm requested changes
Add a test for scenarios where a user hasn't provided a configuration file.

2024-01-08 09:50 UTC, irenebm requested changes

2024-01-08 09:53 UTC, Tempate commented on fastddsspy_tool/test/application/test_cases/one_shot_topics_dds_no_config.py
> +# Copyright 2023 Proyectos y Sistemas de Mantenimiento SL (eProsima).
It's what happens when you take a year to review my PRs...

2024-01-08 14:00 UTC, irenebm commented on fastddsspy_tool/test/application/test_cases/one_shot_topics_dds_no_config.py
> +# Copyright 2023 Proyectos y Sistemas de Mantenimiento SL (eProsima).
Cheers to the power of patience and precision! Like a fine wine, my PRs took time to mature, and the celebration is just as sweet. Here's to the art of meticulous review and the joy of progress!

2024-01-08 14:00 UTC, irenebm approved these changes
LGTM

2024-01-08 14:14 UTC, merged