Configure the domain through the command-line
eProsima/Fast-DDS-spy pull request #82
Opened 2024-04-02 10:44 UTC by Tempate

2024-04-04 08:46 UTC, LuciaEchevarria99 requested changes

2024-04-04 08:46 UTC, LuciaEchevarria99 commented on docs/rst/user_manual/tool.rst
> +       --log-verbosity  Set a Log Verbosity Level higher or equal the one given. (Values accepted: "info","warning","error" no Case Sensitive) [Default = "warning"].
Log verbosity is now Error by default

2024-04-04 10:37 UTC, LuciaEchevarria99 submitted a review, later dismissed
LGTM

2024-04-09 12:07 UTC, rsanchez15 approved these changes

2024-04-09 12:07 UTC, merged