Update repository for Fast DDS 3.0.0 compatibility
eProsima/Fast-DDS-spy pull request #86
Opened 2024-05-20 13:36 UTC by LuciaEchevarria99

Merge after:
-  **Fast-DDS:** https://github.com/eProsima/Fast-DDS/pull/4779
- **dev-utils:** https://github.com/eProsima/dev-utils/pull/101
- **DDS-Pipe:** https://github.com/eProsima/DDS-Pipe/pull/111

2024-09-02 12:42 UTC, juanlofer-eprosima requested changes

2024-09-02 12:42 UTC, juanlofer-eprosima commented on fastddsspy_participants/include/fastddsspy_participants/model/NetworkDatabase.hpp
> +#include <fastdds/dds/xtypes/dynamic_types/DynamicType.hpp>
```suggestion
```

2024-09-02 12:42 UTC, juanlofer-eprosima commented on fastddsspy_participants/test/unittest/model/DataStreamerTest.cpp
> +    // // Opción 1:
Please tidy up.

2024-09-02 12:42 UTC, juanlofer-eprosima commented on fastddsspy_tool/src/cpp/tool/Controller.cpp
> +    auto ret = fastdds::dds::json_serialize(dyn_data, fastdds::dds::DynamicDataJsonFormat::EPROSIMA, ss);
Print error if not OK?

2024-09-15 18:52 UTC, LuciaEchevarria99 commented on fastddsspy_tool/src/cpp/tool/Controller.cpp
> +    auto ret = fastdds::dds::json_serialize(dyn_data, fastdds::dds::DynamicDataJsonFormat::EPROSIMA, ss);
I decided to put a warning

2024-09-16 10:08 UTC, juanlofer-eprosima requested changes

2024-09-16 10:08 UTC, juanlofer-eprosima commented on fastddsspy_tool/test/labels/XTSAN.list
> +<<<<<<< Updated upstream
Fix this.

2024-09-16 14:37 UTC, juanlofer-eprosima approved these changes
LGTM

2024-09-16 15:01 UTC, merged